all:
	javac *.java -classpath ./mongo-java-driver-2.12.4.jar;
	java -cp mongo-java-driver-2.12.4.jar:. Main DJs stfstj 
stj:
	javac *.java -classpath ./mongo-java-driver-2.12.4.jar;
	java -cp mongo-java-driver-2.12.4.jar:. Main DJs stj

stf:
	javac *.java -classpath ./mongo-java-driver-2.12.4.jar;
	java -cp mongo-java-driver-2.12.4.jar:. Main DJs stf
init:
	mongod
