all:
	javac *.java -classpath ./mongo-java-driver-2.12.4.jar;
	java -cp mongo-java-driver-2.12.4.jar:. Main DJs linksALL

stj:
	javac *.java -classpath ./mongo-java-driver-2.12.4.jar;
	java -cp mongo-java-driver-2.12.4.jar:. Main DJs linksSTJ 

stf:
	javac *.java -classpath ./mongo-java-driver-2.12.4.jar;
	java -cp mongo-java-driver-2.12.4.jar:. Main DJs linksSTF 

 
init:
	mongod
