from scrapy.item import Item, Field

class StfItem(Item):
    acordaoId   = Field()
    localSigla  = Field()
    local       = Field()
 #   tipo        = Field()
    relator     = Field()
 #   orgaoJulg   = Field()
    dataJulg    = Field()
#    fontePublic = Field()
    ementa      = Field()
    decisao     = Field()
    citacoes    = Field()
    acordaosSimilares  = Field()
    legislacao  = Field()
    observacao  = Field()
    doutrinas   = Field()
    tags        = Field()
    partes      = Field()
    tribunal    = Field()
    orgaoJulg   = Field()
    index       = Field()
#    acordaos    = Field()
#    tudo        = Field()

class StfLawItem(Item):
    tipo   = Field()
    ano    = Field()
    numero = Field()
