from scrapy.item import Item, Field

class StfItem(Item):
    acordaoId   = Field()
    uf          = Field()
 #   tipo        = Field()
    relator     = Field()
 #   orgaoJulg   = Field()
    dataJulg    = Field()
#    fontePublic = Field()
    ementa      = Field()
    decisao     = Field()
    citacoes    = Field()
    filename    = Field()
#    sucessivos  = Field()
    legislacao  = Field()
    observacao  = Field()
    doutrinas   = Field()
    tags        = Field()
    partes      = Field()
#    acordaos    = Field()
#    tudo        = Field()
